import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { platformGuard } from './core/guards/platform.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./paginas/inicio/inicio.component').then(m => m.InicioComponent) },
  { path: 'autenticacao', loadComponent: () => import('./paginas/login/login.component').then(m => m.LoginComponent) },
  { path: 'esqueci-a-senha', loadComponent: () => import('./paginas/auth/esqueci-senha.component').then(m => m.EsqueciSenhaComponent) },
  { path: 'redefinir-senha', loadComponent: () => import('./paginas/auth/redefinir-senha.component').then(m => m.RedefinirSenhaComponent) },
  { path: 'verificar-email', loadComponent: () => import('./paginas/auth/verificar-email.component').then(m => m.VerificarEmailComponent) },
  { path: 'verificacao-pendente', loadComponent: () => import('./paginas/auth/verificacao-pendente.component').then(m => m.VerificacaoPendenteComponent) },
  { path: 'comece', loadComponent: () => import('./paginas/comece/comece.component').then(m => m.ComeceComponent) },
  { path: 'termos-de-uso', loadComponent: () => import('./paginas/termos/termos.component').then(m => m.TermosComponent) },
  { path: 'privacidade', loadComponent: () => import('./paginas/privacidade/privacidade.component').then(m => m.PrivacidadeComponent) },
  { path: 'f/sucesso', loadComponent: () => import('./paginas/formulario-publico/formulario-publico-sucesso.component').then(m => m.FormularioPublicoSucessoComponent) },
  { path: 'f/:token', loadComponent: () => import('./paginas/formulario-publico/formulario-publico-show.component').then(m => m.FormularioPublicoShowComponent) },
  { path: 'l/:slug', loadComponent: () => import('./paginas/link-bio-public/link-bio-public.component').then(m => m.LinkBioPublicComponent) },
  {
    path: '',
    loadComponent: () => import('./componentes/layout/layout-app/layout-app.component').then(m => m.LayoutAppComponent),
    canActivate: [authGuard],
    children: [
      { path: 'dashboard', loadComponent: () => import('./paginas/dashboard/dashboard.component').then(m => m.DashboardComponent), data: { titulo: 'Dashboard' } },
      { path: 'billing', loadComponent: () => import('./paginas/billing/billing.component').then(m => m.BillingComponent), data: { titulo: 'Assinatura' } },
      { path: 'links-publicos', loadComponent: () => import('./paginas/links-publicos/links-publicos.component').then(m => m.LinksPublicosComponent), data: { titulo: 'Links para enviar' } },
      { path: 'envios', loadComponent: () => import('./paginas/envios/envios.component').then(m => m.EnviosComponent), data: { titulo: 'Envios de documento' } },
      { path: 'protocolos', loadComponent: () => import('./paginas/protocolos/protocolos-listagem.component').then(m => m.ProtocolosListagemComponent), data: { titulo: 'Protocolos' } },
      { path: 'protocolos/:id', loadComponent: () => import('./paginas/protocolos/protocolos-detalhe.component').then(m => m.ProtocolosDetalheComponent), data: { titulo: 'Detalhe do protocolo' } },
      { path: 'notificacoes', loadComponent: () => import('./paginas/notificacoes/notificacoes.component').then(m => m.NotificacoesComponent), data: { titulo: 'Notificações' } },
      { path: 'templates', loadComponent: () => import('./paginas/templates/templates-listagem.component').then(m => m.TemplatesListagemComponent), data: { titulo: 'Templates' } },
      { path: 'templates/criar', loadComponent: () => import('./paginas/templates/templates-criar.component').then(m => m.TemplatesCriarComponent), data: { titulo: 'Novo template', urlVoltar: '/templates', labelVoltar: 'Voltar para Templates' } },
      { path: 'templates/criar-em-branco', loadComponent: () => import('./paginas/templates/templates-criar-em-branco.component').then(m => m.TemplatesCriarEmBrancoComponent), data: { titulo: 'Novo template (em branco)', urlVoltar: '/templates/criar', labelVoltar: 'Voltar à escolha de modelo' } },
      { path: 'templates/:id/editar', loadComponent: () => import('./paginas/templates/templates-editar.component').then(m => m.TemplatesEditarComponent), data: { titulo: 'Editar template', urlVoltar: '/templates', labelVoltar: 'Voltar para Templates' } },
      { path: 'templates/:id/campos', loadComponent: () => import('./paginas/templates/templates-campos.component').then(m => m.TemplatesCamposComponent), data: { titulo: 'Campos', urlVoltar: '/templates', labelVoltar: 'Voltar para Templates' } },
      { path: 'clinica/configuracoes', loadComponent: () => import('./paginas/clinica/clinica-configuracoes.component').then(m => m.ClinicaConfiguracoesComponent), data: { titulo: 'Configurações' } },
      { path: 'clinica/escolher', loadComponent: () => import('./paginas/clinica/clinica-escolher.component').then(m => m.ClinicaEscolherComponent), data: { titulo: 'Escolher empresa' } },
      { path: 'clinica/integracoes', loadComponent: () => import('./paginas/clinica/clinica-integracoes.component').then(m => m.ClinicaIntegracoesComponent), data: { titulo: 'Integrações', urlVoltar: '/clinica/configuracoes', labelVoltar: 'Empresa' } },
      { path: 'link-bio', loadComponent: () => import('./paginas/link-bio/link-bio.component').then(m => m.LinkBioComponent), data: { titulo: 'Link Bio' } },
      { path: 'usuarios', loadComponent: () => import('./paginas/usuarios/usuarios-listagem.component').then(m => m.UsuariosListagemComponent), data: { titulo: 'Usuários' } },
      { path: 'usuarios/criar', loadComponent: () => import('./paginas/usuarios/usuarios-criar.component').then(m => m.UsuariosCriarComponent), data: { titulo: 'Novo usuário' } },
    ],
  },
  {
    path: 'plataforma',
    loadComponent: () => import('./componentes/layout/layout-plataforma/layout-plataforma.component').then(m => m.LayoutPlataformaComponent),
    canActivate: [authGuard, platformGuard],
    children: [
      { path: '', loadComponent: () => import('./paginas/plataforma/plataforma-dashboard/plataforma-dashboard.component').then(m => m.PlataformaDashboardComponent), data: { titulo: 'Visão geral' } },
      { path: 'clientes', loadComponent: () => import('./paginas/plataforma/plataforma-clientes/plataforma-clientes.component').then(m => m.PlataformaClientesComponent), data: { titulo: 'Clientes (tenants)', subtitulo: 'Visão geral dos clientes utilizando o Zion Med.' } },
      { path: 'clientes/:id', loadComponent: () => import('./paginas/plataforma/plataforma-cliente-detalhe/plataforma-cliente-detalhe.component').then(m => m.PlataformaClienteDetalheComponent), data: { titulo: 'Cliente', urlVoltar: '/plataforma/clientes', labelVoltar: 'Voltar para Clientes' } },
      { path: 'leads', loadComponent: () => import('./paginas/plataforma/plataforma-leads/plataforma-leads.component').then(m => m.PlataformaLeadsComponent), data: { titulo: 'Leads', subtitulo: 'Solicitações de demonstração da landing.' } },
      { path: 'notificacoes', loadComponent: () => import('./paginas/notificacoes/notificacoes.component').then(m => m.NotificacoesComponent), data: { titulo: 'Notificações', subtitulo: 'Central de notificações.' } },
      { path: 'assinaturas', loadComponent: () => import('./paginas/plataforma/plataforma-assinaturas/plataforma-assinaturas.component').then(m => m.PlataformaAssinaturasComponent), data: { titulo: 'Assinaturas', subtitulo: 'Visão geral das assinaturas por cliente e empresa.' } },
      { path: 'faturas', loadComponent: () => import('./paginas/plataforma/plataforma-faturas/plataforma-faturas.component').then(m => m.PlataformaFaturasComponent), data: { titulo: 'Faturas / cobranças', subtitulo: 'Visão geral das faturas e cobranças por cliente e empresa.' } },
      { path: 'planos', loadComponent: () => import('./paginas/plataforma/plataforma-planos/plataforma-planos.component').then(m => m.PlataformaPlanosComponent), data: { titulo: 'Planos' } },
      { path: 'planos/novo', loadComponent: () => import('./paginas/plataforma/plataforma-plano-form/plataforma-plano-form.component').then(m => m.PlataformaPlanoFormComponent), data: { titulo: 'Novo plano', urlVoltar: '/plataforma/planos', labelVoltar: 'Voltar para Planos' } },
      { path: 'planos/:id/editar', loadComponent: () => import('./paginas/plataforma/plataforma-plano-form/plataforma-plano-form.component').then(m => m.PlataformaPlanoFormComponent), data: { titulo: 'Editar plano', urlVoltar: '/plataforma/planos', labelVoltar: 'Voltar para Planos' } },
      { path: 'configuracoes', loadComponent: () => import('./paginas/plataforma/plataforma-configuracoes/plataforma-configuracoes.component').then(m => m.PlataformaConfiguracoesComponent), data: { titulo: 'Configurações da plataforma', subtitulo: 'Parâmetros editáveis (banco). API e URL continuam no .env.' } },
      { path: 'logs', loadComponent: () => import('./paginas/plataforma/plataforma-logs/plataforma-logs.component').then(m => m.PlataformaLogsComponent), data: { titulo: 'Meus logs de auditoria', subtitulo: 'Ações realizadas por você na plataforma' } },
    ],
  },
  { path: '404', loadComponent: () => import('./paginas/erro/erro-404.component').then(m => m.Erro404Component) },
  { path: '**', redirectTo: '404' },
];
