import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { platformGuard } from './core/guards/platform.guard';
import { permissionGuard } from './core/guards/permission.guard';
import { canSwitchOrganizationGuard } from './core/guards/can-switch-organization.guard';

export const routes: Routes = [
  { path: 'autenticacao', loadComponent: () => import('./paginas/login/login.component').then(m => m.LoginComponent) },
  { path: 'esqueci-a-senha', loadComponent: () => import('./paginas/auth/esqueci-senha.component').then(m => m.EsqueciSenhaComponent) },
  { path: 'redefinir-senha', loadComponent: () => import('./paginas/auth/redefinir-senha.component').then(m => m.RedefinirSenhaComponent) },
  { path: 'verificar-email', loadComponent: () => import('./paginas/auth/verificar-email.component').then(m => m.VerificarEmailComponent) },
  { path: 'verificacao-pendente', loadComponent: () => import('./paginas/auth/verificacao-pendente.component').then(m => m.VerificacaoPendenteComponent) },
  { path: 'comece', loadComponent: () => import('./paginas/comece/comece.component').then(m => m.ComeceComponent) },
  { path: 'termos-de-uso', loadComponent: () => import('./paginas/termos/termos.component').then(m => m.TermosComponent) },
  { path: 'privacidade', loadComponent: () => import('./paginas/privacidade/privacidade.component').then(m => m.PrivacidadeComponent) },
  { path: 'f/sucesso', loadComponent: () => import('./paginas/formulario-publico/formulario-publico-sucesso.component').then(m => m.FormularioPublicoSucessoComponent) },
  { path: 'f/:token', loadComponent: () => import('./paginas/formulario-publico/formulario-publico-show.component').then(m => m.FormularioPublicoShowComponent) },
  { path: 'templates/:id/preview', canActivate: [authGuard, permissionGuard], loadComponent: () => import('./paginas/templates/templates-preview.component').then(m => m.TemplatesPreviewComponent), data: { titulo: 'Pre-visualizacao do modelo', permission: 'templates.manage' } },
  { path: 'l/demo/:model', loadComponent: () => import('./paginas/demo/demo-link-bio.component').then(m => m.DemoLinkBioComponent) },
  { path: 'l/:slug', loadComponent: () => import('./paginas/link-bio-public/link-bio-public.component').then(m => m.LinkBioPublicComponent) },
  {
    path: '',
    loadComponent: () => import('./componentes/layout/layout-app/layout-app.component').then(m => m.LayoutAppComponent),
    canActivate: [authGuard],
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', canActivate: [permissionGuard], loadComponent: () => import('./paginas/dashboard/dashboard.component').then(m => m.DashboardComponent), data: { titulo: 'Painel', permission: 'dashboard.access' } },
      { path: 'billing', redirectTo: 'assinatura', pathMatch: 'full' },
      {
        path: 'assinatura',
        canActivate: [permissionGuard],
        loadComponent: () => import('./paginas/billing/billing.component').then(m => m.BillingComponent),
        data: { titulo: 'Assinatura', permission: 'billing.manage' },
      },
      { path: 'links-publicos', canActivate: [permissionGuard], loadComponent: () => import('./paginas/links-publicos/links-publicos.component').then(m => m.LinksPublicosComponent), data: { titulo: 'Links para enviar', permissionAny: ['templates.manage', 'submissions.view'] } },
      { path: 'envios', canActivate: [permissionGuard], loadComponent: () => import('./paginas/envios/envios.component').then(m => m.EnviosComponent), data: { titulo: 'Envios de documento', permissionAny: ['templates.manage', 'submissions.view'] } },
      { path: 'protocolos', canActivate: [permissionGuard], loadComponent: () => import('./paginas/protocolos/protocolos-listagem.component').then(m => m.ProtocolosListagemComponent), data: { titulo: 'Protocolos', permission: 'submissions.view' } },
      { path: 'protocolos/:id', canActivate: [permissionGuard], loadComponent: () => import('./paginas/protocolos/protocolos-detalhe.component').then(m => m.ProtocolosDetalheComponent), data: { titulo: 'Detalhe do protocolo', permission: 'submissions.view', urlVoltar: '/protocolos', labelVoltar: 'Voltar para Protocolos' } },
      { path: 'pessoas', canActivate: [permissionGuard], loadComponent: () => import('./paginas/pessoas/pessoas-listagem.component').then(m => m.PessoasListagemComponent), data: { titulo: 'Pessoas', permission: 'submissions.view' } },
      { path: 'pessoas/criar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/pessoas/pessoas-formulario.component').then(m => m.PessoasFormularioComponent), data: { titulo: 'Nova pessoa', permission: 'submissions.view', urlVoltar: '/pessoas', labelVoltar: 'Voltar para Pessoas' } },
      { path: 'pessoas/:id/editar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/pessoas/pessoas-formulario.component').then(m => m.PessoasFormularioComponent), data: { titulo: 'Editar pessoa', permission: 'submissions.view', urlVoltar: '/pessoas', labelVoltar: 'Voltar para Pessoas' } },
      { path: 'pessoas/:id', canActivate: [permissionGuard], loadComponent: () => import('./paginas/pessoas/pessoas-detalhe.component').then(m => m.PessoasDetalheComponent), data: { titulo: 'Ficha da pessoa', permission: 'submissions.view', urlVoltar: '/pessoas', labelVoltar: 'Voltar para Pessoas' } },
      { path: 'notificacoes', canActivate: [permissionGuard], loadComponent: () => import('./paginas/notificacoes/notificacoes.component').then(m => m.NotificacoesComponent), data: { titulo: 'Notificações', permission: 'notifications.access' } },
      { path: 'templates', canActivate: [permissionGuard], loadComponent: () => import('./paginas/templates/templates-listagem.component').then(m => m.TemplatesListagemComponent), data: { titulo: 'Modelos de fichas', permission: 'templates.manage' } },
      { path: 'templates/criar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/templates/templates-criar.component').then(m => m.TemplatesCriarComponent), data: { titulo: 'Novo modelo', permission: 'templates.manage', urlVoltar: '/templates', labelVoltar: 'Voltar para modelos' } },
      { path: 'templates/criar-em-branco', canActivate: [permissionGuard], loadComponent: () => import('./paginas/templates/templates-criar-em-branco.component').then(m => m.TemplatesCriarEmBrancoComponent), data: { titulo: 'Novo modelo (em branco)', permission: 'templates.manage', urlVoltar: '/templates/criar', labelVoltar: 'Voltar à escolha de modelo' } },
      { path: 'templates/:id/editar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/templates/templates-editar.component').then(m => m.TemplatesEditarComponent), data: { titulo: 'Editar modelo', permission: 'templates.manage', urlVoltar: '/templates', labelVoltar: 'Voltar para modelos' } },
      { path: 'templates/:id/campos', canActivate: [permissionGuard], loadComponent: () => import('./paginas/templates/templates-campos.component').then(m => m.TemplatesCamposComponent), data: { titulo: 'Campos do modelo', permission: 'templates.manage', urlVoltar: '/templates', labelVoltar: 'Voltar para modelos' } },
      { path: 'clinica/configuracoes', canActivate: [permissionGuard], loadComponent: () => import('./paginas/clinica/clinica-configuracoes.component').then(m => m.ClinicaConfiguracoesComponent), data: { titulo: 'Configurações', permission: 'organization.manage' } },
      { path: 'clinica/escolher', canActivate: [canSwitchOrganizationGuard], loadComponent: () => import('./paginas/clinica/clinica-escolher.component').then(m => m.ClinicaEscolherComponent), data: { titulo: 'Escolher empresa', urlVoltar: '/dashboard', labelVoltar: 'Painel' } },
      { path: 'clinica/integracoes', canActivate: [permissionGuard], loadComponent: () => import('./paginas/clinica/clinica-integracoes.component').then(m => m.ClinicaIntegracoesComponent), data: { titulo: 'Integrações', permission: 'organization.manage', urlVoltar: '/clinica/configuracoes', labelVoltar: 'Empresa' } },
      { path: 'clinica/integracoes/sistemas/feegow', canActivate: [permissionGuard], loadComponent: () => import('./paginas/clinica/clinica-integracao-feegow.component').then(m => m.ClinicaIntegracaoFeegowComponent), data: { titulo: 'Integração Feegow', permission: 'organization.manage', urlVoltar: '/clinica/integracoes', labelVoltar: 'Integrações' } },
      { path: 'link-bio', canActivate: [permissionGuard], loadComponent: () => import('./paginas/link-bio/link-bio.component').then(m => m.LinkBioComponent), data: { titulo: 'Página de links', permission: 'organization.manage', urlVoltar: '/clinica/configuracoes', labelVoltar: 'Empresa' } },
      { path: 'usuarios', canActivate: [permissionGuard], loadComponent: () => import('./paginas/usuarios/usuarios-listagem.component').then(m => m.UsuariosListagemComponent), data: { titulo: 'Usuários', permission: 'users.manage' } },
      { path: 'usuarios/criar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/usuarios/usuarios-formulario.component').then(m => m.UsuariosFormularioComponent), data: { titulo: 'Novo usuário', permission: 'users.manage', urlVoltar: '/usuarios', labelVoltar: 'Voltar para Usuários' } },
      { path: 'usuarios/:id/editar', canActivate: [permissionGuard], loadComponent: () => import('./paginas/usuarios/usuarios-formulario.component').then(m => m.UsuariosFormularioComponent), data: { titulo: 'Editar usuário', permission: 'users.manage', urlVoltar: '/usuarios', labelVoltar: 'Voltar para Usuários' } },
      { path: 'organizacao/permissoes', canActivate: [permissionGuard], loadComponent: () => import('./paginas/organizacao/organizacao-papeis-listagem.component').then(m => m.OrganizacaoPapeisListagemComponent), data: { titulo: 'Permissões', permission: 'users.manage', urlVoltar: '/usuarios', labelVoltar: 'Usuários' } },
      { path: 'organizacao/permissoes/:slug', canActivate: [permissionGuard], loadComponent: () => import('./paginas/organizacao/organizacao-papel-formulario.component').then(m => m.OrganizacaoPapelFormularioComponent), data: { titulo: 'Permissões', permission: 'users.manage', urlVoltar: '/organizacao/permissoes', labelVoltar: 'Voltar às permissões' } },
    ],
  },
  {
    path: 'plataforma',
    loadComponent: () => import('./componentes/layout/layout-plataforma/layout-plataforma.component').then(m => m.LayoutPlataformaComponent),
    canActivate: [authGuard, platformGuard],
    children: [
      { path: '', loadComponent: () => import('./paginas/plataforma/plataforma-dashboard/plataforma-dashboard.component').then(m => m.PlataformaDashboardComponent), data: { titulo: 'Visão geral' } },
      { path: 'clientes', loadComponent: () => import('./paginas/plataforma/plataforma-clientes/plataforma-clientes.component').then(m => m.PlataformaClientesComponent), data: { titulo: 'Clientes (tenants)', subtitulo: 'Visão geral dos clientes utilizando o Gestgo.' } },
      { path: 'clientes/:id', loadComponent: () => import('./paginas/plataforma/plataforma-cliente-detalhe/plataforma-cliente-detalhe.component').then(m => m.PlataformaClienteDetalheComponent), data: { titulo: 'Cliente', urlVoltar: '/plataforma/clientes', labelVoltar: 'Voltar para Clientes' } },
      { path: 'leads', loadComponent: () => import('./paginas/plataforma/plataforma-leads/plataforma-leads.component').then(m => m.PlataformaLeadsComponent), data: { titulo: 'Leads', subtitulo: 'Solicitações de demonstração da landing.' } },
      { path: 'notificacoes', loadComponent: () => import('./paginas/notificacoes/notificacoes.component').then(m => m.NotificacoesComponent), data: { titulo: 'Notificações', subtitulo: 'Central de notificações.' } },
      { path: 'assinaturas', loadComponent: () => import('./paginas/plataforma/plataforma-assinaturas/plataforma-assinaturas.component').then(m => m.PlataformaAssinaturasComponent), data: { titulo: 'Assinaturas', subtitulo: 'Visão geral das assinaturas por cliente e empresa.' } },
      { path: 'faturas', loadComponent: () => import('./paginas/plataforma/plataforma-faturas/plataforma-faturas.component').then(m => m.PlataformaFaturasComponent), data: { titulo: 'Faturas / cobranças', subtitulo: 'Visão geral das faturas e cobranças por cliente e empresa.' } },
      { path: 'planos', loadComponent: () => import('./paginas/plataforma/plataforma-planos/plataforma-planos.component').then(m => m.PlataformaPlanosComponent), data: { titulo: 'Planos' } },
      { path: 'planos/novo', loadComponent: () => import('./paginas/plataforma/plataforma-plano-form/plataforma-plano-form.component').then(m => m.PlataformaPlanoFormComponent), data: { titulo: 'Novo plano', urlVoltar: '/plataforma/planos', labelVoltar: 'Voltar para Planos' } },
      { path: 'planos/:id/editar', loadComponent: () => import('./paginas/plataforma/plataforma-plano-form/plataforma-plano-form.component').then(m => m.PlataformaPlanoFormComponent), data: { titulo: 'Editar plano', urlVoltar: '/plataforma/planos', labelVoltar: 'Voltar para Planos' } },
      { path: 'configuracoes', loadComponent: () => import('./paginas/plataforma/plataforma-configuracoes/plataforma-configuracoes.component').then(m => m.PlataformaConfiguracoesComponent), data: { titulo: 'Configurações da plataforma', subtitulo: 'Parâmetros editáveis (banco). API e URL continuam no .env.' } },
      { path: 'logs', loadComponent: () => import('./paginas/plataforma/plataforma-logs/plataforma-logs.component').then(m => m.PlataformaLogsComponent), data: { titulo: 'Meus logs de auditoria', subtitulo: 'Ações realizadas por você na plataforma' } },
      {
        path: 'organizacoes-online',
        loadComponent: () =>
          import('./paginas/plataforma/plataforma-organizacoes-online/plataforma-organizacoes-online.component').then(
            (m) => m.PlataformaOrganizacoesOnlineComponent
          ),
        data: { titulo: 'Empresas online', subtitulo: 'Organizações com sessão ativa no app neste momento.' },
      },
    ],
  },
  { path: '404', loadComponent: () => import('./paginas/erro/erro-404.component').then(m => m.Erro404Component) },
  { path: '**', redirectTo: '404' },
];
